# Configuration
#
# Replace the following placeholders with the correct values for
# your installation.
#
# <SEARCH_URL>: The URL for performing the search
# <QUERY_PARAMS>: Any HTTP query parameters that should be included in the search
# <LOADED_LINK>: The direct link to your Database Finder site

defaults: &defaults
  search_url: 'http://localhost:8080/site/dbfinder/restapi/v1/search'
  query_params: '?q='
  loaded_link: 'http://localhost:8080/site/dbfinder/list?queryScope=all&query='

development:
  <<: *defaults

test:
  <<: *defaults

staging:
  <<: *defaults

production:
  <<: *defaults