defaults: &defaults
  search_url: "<%= ENV['DATABASE_FINDER_HIPPO_SITE_URL'] %>/dbfinder/restapi/v1/search"
  query_params: '?q='
  loaded_link: "<%= ENV['DATABASE_FINDER_HIPPO_SITE_URL'] %>/dbfinder/list?queryScope=all&query="

development:
  <<: *defaults

test:
  <<: *defaults

staging:
  <<: *defaults

production:
  <<: *defaults